---
version: "2.1"
services:
  book-a-book-eureka:
    image: aleixmt/book-a-book-eureka:latest
    ports:
      - "0.0.0.0:8761:8761"
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.11.4
    environment:
      - discovery.type=single-node
      - node.name=elasticnode
      - cluster.name=elastic
      - bootstrap.memory_lock=true
#      - ELASTIC_USERNAME=elastic
#      - ELASTIC_PASSWORD=chemistry
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "0.0.0.0:9200:9200"
    restart: unless-stopped

