---
version: "2.1"
services:
  echempad_app:
    image: aleixmt/bookabook:latest
    ports:
      - "0.0.0.0:80:8081"
    restart: unless-stopped

  postgres_db:
    image: postgres
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Etc/UTC
      - POSTGRES_PASSWORD=chemistry
      - POSTGRES_USER=aleixmt
      - POSTGRES_DB=bookabook
    ports:
      - "0.0.0.0:5433:5432"
    restart: unless-stopped